Repository airavata-courses/CAPtivate, pull requests merged in 2020-02, with the labels that each got.

#13 BootStrap Api Server using Scala Http4s
  .gitignore
  api-gateway/build.sbt
  api-gateway/project/build.properties
  api-gateway/project/plugins.sbt
  api-gateway/src/main/resources/logback.xml
  api-gateway/src/main/scala/airavata/github/captivate/apigateway/ApigatewayRoutes.scala
  api-gateway/src/main/scala/airavata/github/captivate/apigateway/ApigatewayServer.scala
  api-gateway/src/main/scala/airavata/github/captivate/apigateway/Main.scala
  api-gateway/src/main/scala/airavata/github/captivate/apigateway/SessionManagement.scala
  api-gateway/src/main/scala/airavata/github/captivate/apigateway/UserManagement.scala
  api-gateway/src/test/scala/airavata/github/captivate/apigateway/ApiGatewaySpec.scala
Labels: Review Required

#19 Add initial CI setup
  .gitignore
  .travis.yml
Labels: Review Required

#23 Initialize Kafka Zookeeper server using docker
  kafka/README.md
  kafka/docker-compose.yml
Labels: Review Required

#25 Get started with kafka producer in API gateway
  api-gateway/build.sbt
  api-gateway/src/main/scala/airavata/github/captivate/apigateway/ApigatewayRoutes.scala
  api-gateway/src/main/scala/airavata/github/captivate/apigateway/ApigatewayServer.scala
  api-gateway/src/test/scala/airavata/github/captivate/apigateway/ApiGatewaySpec.scala
Labels: Review Required

#22 Add minor tests to API gateway and add Readme
  api-gateway/README.md
  api-gateway/src/main/scala/airavata/github/captivate/apigateway/ApigatewayRoutes.scala
  api-gateway/src/test/scala/airavata/github/captivate/apigateway/ApiGatewaySpec.scala
Labels: Review Required

#27 Bootstrap Model execution service
  prediction-service/README.md
  prediction-service/prediction-service.py
Labels: Review Required

#31 Bootstrap data-retrival service
  data-retrieval/README.md
  data-retrieval/data-retrieval.py
Labels: Review Required

#33 Bootstrap session management service
  .gitignore
  session-management/README.md
  session-management/package.json
  session-management/session-management.js
Labels: WIP

#35 Clean-up and Create a flow between services
  data-retrieval/data-retrieval.py
  model-execution/README.md
  model-execution/model-execution.py
  postprocessing-analysis/README.md
  postprocessing-analysis/postprocessing-analysis.py
  postprocessing_analysis/postprocessing_analysis.py
  postprocessing_analysis/producer.py
Labels: Review Required

#34 Fix api gateway to handle data retrieval
  api-gateway/src/main/scala/airavata/github/captivate/apigateway/ApigatewayRoutes.scala
  api-gateway/src/main/scala/airavata/github/captivate/apigateway/ApigatewayServer.scala
  api-gateway/src/main/scala/airavata/github/captivate/apigateway/DataRetrieval.scala
  api-gateway/src/test/scala/airavata/github/captivate/apigateway/ApiGatewaySpec.scala
Labels: Review Required

#36 Bootstrap basic login using user-management service
  WeatherApp/.gitignore
  WeatherApp/package.json
  WeatherApp/public/favicon.ico
  WeatherApp/public/index.html
  WeatherApp/public/logo192.png
  WeatherApp/public/logo512.png
  WeatherApp/public/manifest.json
  WeatherApp/public/robots.txt
  WeatherApp/src/App.css
  WeatherApp/src/App.js
  WeatherApp/src/App.test.js
  WeatherApp/src/Dashboard.js
  WeatherApp/src/Home.js
  WeatherApp/src/Login.js
  WeatherApp/src/Utils/Common.js
  WeatherApp/src/Utils/PrivateRoute.js
  WeatherApp/src/Utils/PublicRoute.js
  WeatherApp/src/Weather.js
  WeatherApp/src/components/content/Jobs.js
  WeatherApp/src/components/content/WeatherData.js
  WeatherApp/src/img/bg.jpg
  WeatherApp/src/index.css
  WeatherApp/src/logo0.svg
  WeatherApp/src/serviceWorker.js
  WeatherApp/src/setupTests.js
Labels: WIP

#37 Configuration-updated topic names
  kafka/docker-compose.yml
Labels: enhancement

#38 Fix Messaging across all the services
  data-retrieval/data-retrieval.py
  kafka/docker-compose.yml
  model-execution/model-execution.py
  postprocessing-analysis/postprocessing-analysis.py
  session-management/README.md
  session-management/session-management.js
Labels: Review Required

#39 Implement get sessions by user id
  api-gateway/src/main/scala/airavata/github/captivate/apigateway/ApigatewayRoutes.scala
  data-retrieval/data-retrieval.py
  session-management/session-management.js
Labels: Review Required

#40 Fix CORS issue in API Gateway
  api-gateway/src/main/scala/airavata/github/captivate/apigateway/ApigatewayServer.scala
Labels: Review Required

#43 Update README with instructions to test project
  README.md
Labels: documentation

#45 Fix Mongo containter names in READMEs
  data-retrieval/README.md
  model-execution/README.md
  postprocessing-analysis/README.md
  session-management/README.md
Labels: Review Required

#59 Improve data retrieval service
  data-retrieval/data-retrieval.py
Labels: Review Required

#62 Improve Model-execution and Post-processing services
  model-execution/model-execution.py
  postprocessing-analysis/postprocessing-analysis.py
Labels: Review Required

#66 Handle future dates and validate date string in Data retrieval
  data-retrieval/data-retrieval.py
Labels: Review Required

#69 Fix issue with date time format
  data-retrieval/data-retrieval.py
Labels: Review Required

#70 Add CORS support in session management
  session-management/package.json
  session-management/session-management.js
Labels: Review Required

#74 Fix status field in message
  data-retrieval/data-retrieval.py
Labels: WIP
